version: "3.2"
services:
    postgres:
        ports:
            - "5432:5432"
        image: postgres:14
        command: psql -d upchieve -f $HOME/schema/schema.sql
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=Password123
        volumes:
            - $HOME/upchieve/postgres-volume:/var/lib/postgresql/data
            - $HOME/upchieve/subway/db-schema/db/schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    mongodb:
        ports:
            - "27017-27019:27017-27019"
        image: mongo:4.4.5
        environment:
            - MONGO_INITDB_DATABASE=upchieve
        volumes:
            - $HOME/upchieve/mongo-volume:/data/db
    redis:
        ports:
            - "6379:6379"
        image: redis:6.2.1
        volumes:
            - $HOME/upchieve/redis-volume:/data
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "80:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@upchieve.org
            - PGADMIN_DEFAULT_PASSWORD=Password123
        restart: unless-stopped
