allowBuilds:
  '@firebase/util': true
  '@newrelic/fn-inspect': true
  '@newrelic/native-metrics': true
  '@scarf/scarf': true
  '@sentry-internal/node-cpu-profiler': true
  bcrypt: true
  canvas: true
  esbuild: true
  pg-formatter: true
  pre-commit: true
  protobufjs: true
  sharp: true
  spawn-sync: true

blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3' # ts-node-dev and @pgtyped/cli need to fix upstream
  - 'semver@6.3.1' # jest needs to fix upstream. we could migrate to vitest to fix this one
  - 'jose@4.15.9' # major bump from firebase-admin 13 to 14 will fix this one
