import { wrapInsert, NameToId, getDbUlid } from '../utils'
import * as pgQueries from './pg.queries'

export async function studentPartnerOrgsReal(): Promise<NameToId> {
  const orgs = [
    {
      id: getDbUlid(),
      key: 'edready',
      name: 'EdReady',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'EDREADY',
    },
    {
      id: getDbUlid(),
      key: 'citysquash',
      name: 'CitySquash',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: true,
      signupCode: 'CSQUASH',
    },
    {
      id: getDbUlid(),
      key: 'school-closure',
      name: 'School Closure',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'CLOSURE',
    },
    {
      id: getDbUlid(),
      key: 'queens-library',
      name: 'Queens Library',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: true,
      signupCode: 'QPL',
    },
    {
      id: getDbUlid(),
      key: 'oasis',
      name: 'OASIS',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: true,
      signupCode: 'OASIS',
    },
    {
      id: getDbUlid(),
      key: 'summer-search',
      name: 'Summer Search',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: true,
      signupCode: 'SUMMERS',
    },
    {
      id: getDbUlid(),
      key: 'mindsmatter-co',
      name: 'Minds Matter Colorado',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'MINDSM',
    },
    {
      id: getDbUlid(),
      key: 'btny',
      name: 'BTNY',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'BTNY',
    },
    {
      id: getDbUlid(),
      key: 'college-track',
      name: 'College Track',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'CTRACK',
    },
    {
      id: getDbUlid(),
      key: 'spark',
      name: 'Spark',
      highSchoolSignup: false,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'SPARK',
    },
    {
      id: getDbUlid(),
      key: 'nyc-mission',
      name: 'NYC Mission Society',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'MISSION',
    },
    {
      id: getDbUlid(),
      key: 'college-is-real',
      name: 'College is Real',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'CIR',
    },
    {
      id: getDbUlid(),
      key: 'south-bronx-united',
      name: 'South Bronx United',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'SBU',
    },
    {
      id: getDbUlid(),
      key: 'eligibility-appeal',
      name: 'Eligibility Appeal',
      highSchoolSignup: true,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'APPEAL',
    },
    {
      id: getDbUlid(),
      key: 'bhcfl',
      name: 'BHCFL',
      highSchoolSignup: false,
      collegeSignup: false,
      schoolSignupRequired: false,
      signupCode: 'BHCFL',
    },
    {
      id: getDbUlid(),
      key: '10kdegrees',
      name: '10,000 Degrees',
      highSchoolSignup: true,
      collegeSignup: true,
      schoolSignupRequired: true,
      signupCode: '10K',
    },
    {
      id: getDbUlid(),
      key: 'bgcb',
      name: 'BGCB',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'BGCB',
    },
    {
      id: getDbUlid(),
      key: 'btsf',
      name: 'BTSF',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'BTSF',
    },
    {
      id: getDbUlid(),
      key: 'assistments',
      name: 'ASSISTments',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'ASSIST',
    },
    {
      id: getDbUlid(),
      key: 'att-connected-learning',
      name: 'AT&T Connected Learning',
      highSchoolSignup: true,
      schoolSignupRequired: true,
      collegeSignup: false,
      signupCode: 'CLC',
    },
    {
      id: getDbUlid(),
      key: 'cis-mid-america',
      name: 'CIS Mid-America',
      highSchoolSignup: true,
      schoolSignupRequired: true,
      collegeSignup: false,
      signupCode: 'CISMA',
    },
    {
      id: getDbUlid(),
      key: 'beat-the-streets',
      name: 'Beat the Streets',
      highSchoolSignup: true,
      schoolSignupRequired: true,
      collegeSignup: false,
      signupCode: 'BTS',
    },
    {
      id: getDbUlid(),
      key: 'nac',
      name: 'NAC',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'NAC',
    },
    {
      id: getDbUlid(),
      key: 'chinatown-cdc',
      name: 'Chinatown CDC',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'CCDC',
    },
    {
      id: getDbUlid(),
      key: 'cyc',
      name: 'CYC',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'CYC',
    },
    {
      id: getDbUlid(),
      key: 'scdc',
      name: 'SCDC',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'SCDC',
    },
    {
      id: getDbUlid(),
      key: '100-black-men-of-louisville',
      name: '100 Black Men of Louisville',
      highSchoolSignup: true,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'BML',
    },
    {
      id: getDbUlid(),
      key: 'ehtp',
      name: 'EHTP',
      highSchoolSignup: false,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'EHTP',
    },
    {
      id: getDbUlid(),
      key: 'first-graduate',
      name: 'First Graduate',
      highSchoolSignup: false,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'FIRSTGRAD',
    },
    {
      id: getDbUlid(),
      key: 'bbbs-nyc',
      name: 'BBBS NYC',
      highSchoolSignup: false,
      schoolSignupRequired: false,
      collegeSignup: false,
      signupCode: 'BBBS',
    },

  ]
  const temp: NameToId = {}
  for (const org of orgs) {
    temp[org.key] = await wrapInsert(
      'student_partner_orgs',
      pgQueries.insertStudentPartnerOrg.run,
      { ...org }
    )
  }
  return temp
}
