-- General App Role.
-- This role has read/write privileges to both the auth and upchieve schemas.
CREATE ROLE subway;
GRANT ALL privileges ON ALL tables IN SCHEMA upchieve TO subway;
GRANT ALL privileges ON ALL sequences IN SCHEMA upchieve TO subway;
GRANT usage ON SCHEMA upchieve TO subway;
ALTER ROLE subway SET search_path = upchieve;
GRANT ALL privileges ON ALL tables IN SCHEMA auth TO subway;
GRANT ALL privileges ON ALL sequences IN SCHEMA auth TO subway;
GRANT usage ON SCHEMA auth TO subway;
ALTER DEFAULT PRIVILEGES IN SCHEMA upchieve GRANT ALL PRIVILEGES ON tables TO subway;

-- Staff Read-Only Role.
-- This role has read privileges to both the auth and upchieve schemas.
CREATE ROLE staff_ro;
GRANT SELECT ON ALL tables IN SCHEMA upchieve to staff_ro;
GRANT SELECT ON ALL sequences IN SCHEMA upchieve to staff_ro;
GRANT usage ON SCHEMA upchieve to staff_ro;
ALTER ROLE staff_ro SET search_path = upchieve;
GRANT SELECT ON ALL tables IN SCHEMA auth to staff_ro;
GRANT SELECT ON ALL sequences IN SCHEMA auth to staff_ro;
GRANT usage on SCHEMA auth to staff_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA upchieve GRANT SELECT ON tables TO staff_ro;

-- Retool Role.
-- Same as subway role above.
CREATE ROLE retool;
GRANT ALL privileges ON ALL tables IN SCHEMA upchieve TO retool;
GRANT ALL privileges ON ALL sequences IN SCHEMA upchieve TO retool;
GRANT usage ON SCHEMA upchieve TO retool;
ALTER ROLE retool SET search_path = upchieve;
GRANT ALL privileges ON ALL tables IN SCHEMA auth TO retool;
GRANT ALL privileges ON ALL sequences IN SCHEMA auth TO retool;
GRANT usage ON SCHEMA auth TO retool;
ALTER DEFAULT PRIVILEGES IN SCHEMA upchieve GRANT ALL PRIVILEGES ON tables TO retool;

-- mat view owner role
-- subway needs to be able to refresh mat views, which requires ownership,
-- but admin/avnadmin needs superuser control over everything for down migrations to work correctly
CREATE ROLE mat_view_owners;
GRANT CREATE ON SCHEMA upchieve to mat_view_owners;
GRANT SELECT ON ALL tables IN SCHEMA upchieve to mat_view_owners;
ALTER DEFAULT PRIVILEGES IN SCHEMA upchieve GRANT SELECT ON tables TO mat_view_owners;
GRANT mat_view_owners TO subway;
DO $$
BEGIN
  -- this is for local dev db owner user
  GRANT mat_view_owners to admin;
  -- this is for our cloud vendor owner user
  GRANT mat_view_owners TO avnadmin;
EXCEPTION
  -- ignore if one of the above fails because the role doesn't exist
  -- local dev fails if this script has an error so we have to catch and ignore
  WHEN OTHERS THEN NULL;
END;
$$;
-- put all mat view ownership moves below here
ALTER MATERIALIZED VIEW upchieve.current_grade_levels_mview OWNER TO mat_view_owners;
ALTER MATERIALIZED VIEW upchieve.current_grade_levels_mview OWNER TO subway;

-- Analytics Schema and Read-Only Role.
-- analytics schema is regenerated by analytics.rebuild() (see subway/analytics/);
-- analytics_ro is the consumer role for team Claude / Slack Claude / Retool dashboards.
-- Staff who need PII use staff_ro (full read on upchieve).
CREATE SCHEMA IF NOT EXISTS analytics;
GRANT CREATE ON SCHEMA analytics TO subway;
GRANT usage  ON SCHEMA analytics TO subway;

CREATE ROLE analytics_ro;
GRANT usage  ON SCHEMA analytics TO analytics_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO analytics_ro;
ALTER ROLE analytics_ro SET search_path = analytics;
ALTER DEFAULT PRIVILEGES FOR ROLE subway IN SCHEMA analytics
  GRANT SELECT ON TABLES TO analytics_ro;

-- Operational safety knobs.
ALTER ROLE analytics_ro SET statement_timeout = '60s';
ALTER ROLE analytics_ro SET idle_in_transaction_session_timeout = '30s';

-- Analytics Layer 2 Admin Role.
-- Narrow-scope role used by the sync_analytics_layer2_views CI job. Can edit
-- analytics._layer_2_view_defs and call analytics.rebuild(); cannot touch
-- upchieve.* or other analytics objects. Object-level grants on the table
-- and the function are owned by the migration that creates them.
CREATE ROLE analytics_layer2_admin;
GRANT usage ON SCHEMA analytics TO analytics_layer2_admin;

-- Analytics Privacy Admin Role.
-- Used by the sync_masking_rules CI job to reinstall analytics._blanket_rules()
-- and upsert analytics._custom_rules from database/privacy/*.sql. Needs CREATE
-- on the analytics schema to replace the _blanket_rules function. Object-level
-- grants live alongside the table definitions in database/analytics/setup.sql.
-- Mirrors the role created idempotently by the analytics migration.
CREATE ROLE analytics_privacy_admin;
GRANT usage, CREATE ON SCHEMA analytics TO analytics_privacy_admin;
