ALTER ROLE subway WITH LOGIN PASSWORD 'Password123';
ALTER ROLE staff_ro WITH LOGIN PASSWORD 'Password123';
ALTER ROLE retool WITH LOGIN PASSWORD 'Password123';
ALTER ROLE analytics_ro WITH LOGIN PASSWORD 'Password123';
ALTER ROLE analytics_layer2_admin WITH LOGIN PASSWORD 'Password123';
