-- migrate:up
-- DML moved to seed-update 20260709120003_update-standardized-testing-copy so this
-- migration is safe to run on logical-replication subscribers.
-- Left intentionally empty: already-applied environments never re-run this body,
-- and a from-empty build applies the update from the seed-update.
-- migrate:down
