-- migrate:up
-- DML moved to seed-update 20260709120002_add-session-flags-for-automated-moderation
-- so this migration is safe to run on logical-replication subscribers.
-- Left intentionally empty: already-applied environments never re-run this body,
-- and a from-empty build picks up the rows from the seed-update.
-- migrate:down
