import type { LegacyUserPublic, RoleContextPublic } from '../contracts/users'
import type { LegacyUserModel } from '../models/User/legacy-user'
import type { RoleContext } from '../services/UserRolesService'

export function toRoleContextPublic(role: RoleContext): RoleContextPublic {
  return {
    activeRole: role.activeRole,
    legacyRole: role.legacyRole,
    roles: role.roles,
  }
}

export function toLegacyUserPublic(user: LegacyUserModel): LegacyUserPublic {
  return {
    id: user.id,
    _id: user.id,
    firstName: user.firstName,
    firstname: user.firstName,
    lastName: user.lastName,
    createdAt: user.createdAt.toISOString(),
    email: user.email,
    proxyEmail: user.proxyEmail,
    verified: user.verified,
    phone: user.phone,
    college: user.college,
    userType: user.userType,
    isBanned: user.banType === 'complete',
    banType: user.banType,
    banReason: user.banReason,
    roleContext: toRoleContextPublic(user.roleContext),
    isTestUser: user.isTestUser,
    isFakeUser: user.isFakeUser,
    isDeactivated: user.isDeactivated,
    pastSessions: user.pastSessions,
    lastActivityAt: user.lastActivityAt?.toISOString(),
    referralCode: user.referralCode,
    numReferredVolunteers: user.numReferredVolunteers,
    referredBy: user.referredBy,
    sessionStats: user.sessionStats,
    preferredLanguage: user.preferredLanguage,
    signupSource: user.signupSource,
    isOnboarded: user.isOnboarded,
    isApproved: user.isApproved,
    volunteerPartnerOrg: user.volunteerPartnerOrg,
    subjects: user.subjects,
    activeSubjects: user.activeSubjects,
    mutedSubjectAlerts: user.mutedSubjectAlerts,
    totalActiveCertifications: user.totalActiveCertifications,
    availability: user.availability,
    certifications: user.certifications,
    availabilityLastModifiedAt: user.availabilityLastModifiedAt?.toISOString(),
    trainingCourses: user.trainingCourses,
    occupation: user.occupation,
    country: user.country,
    timezone: user.timezone,
    totalVolunteerHours: user.totalVolunteerHours,
    hoursTutored: user.hoursTutored,
    hoursTutoredThisWeek: user.hoursTutoredThisWeek,
    elapsedAvailability: user.elapsedAvailability,
    references: user.references,
    photoIdStatus: user.photoIdStatus,
    uniqueStudentsHelpedCount: user.uniqueStudentsHelpedCount,
    hasCompletedVolunteerTraining: user.hasCompletedVolunteerTraining,
    gradeLevel: user.gradeLevel,
    schoolName: user.schoolName,
    latestRequestedSubjects: user.latestRequestedSubjects,
    numberOfStudentClasses: user.numberOfStudentClasses,
    issuers: user.issuers,
    studentPartnerOrg: user.studentPartnerOrg,
    isSchoolPartner: user.isSchoolPartner,
    usesClever: user.usesClever,
    usesGoogle: user.usesGoogle,
    usesClassLink: user.usesClassLink,
    studentAssignments: user.studentAssignments,
    ratings: user.ratings,
    favoriteVolunteers: user.favoriteVolunteers,
    lastSuccessfulCleverSync: user.lastSuccessfulCleverSync?.toISOString(),
    sponsorships: user.sponsorships,
  }
}
