export async function track({ userId, userAgent, ip, clientUUID }) {
  /*
   *
   *  let's take a deviceUUID (generated by high-line) and store that as part of the redis key
   *  then high-line sends it up everytime
   *
   *  example:
   *  1. high-line session created, send up UUID 123
   *  2. ping({UUID: 123}) // great, this is good
   *  3. high-line session loses network connectivity // this is bad
   *  4. 2 minutes later, redis key expires, we add AWAY user action
   *  5. 1 minute later, high-line is back online and pings with UUID 123
   *  6. we create a new redis key // this is good! i think this is what we want
   *
   *  This lets us handle multiple devices online at the same time.
   *  BUT it might be hard to match up ACTIVE and AWAY events if the userAgent
   *  or ip changes between... so now, do we need to store clientUUID???
   *
   *
   * 1. check redis for userId:clientUUID
   *  - if exists "userId:clientUUID"
   *    update ttl
   *  - else
   *     a. create redis entry
   *        - userId:clientUUID
   *          - NOTE: user agent and ip can change within a session. do we care?
   *                  if they change, we'll create a new entry and the old will expire
   *        - set 2 min ttl?
   *        - subscribe to expiration events. on expiration, call end() https://redis.io/docs/latest/develop/pubsub/keyspace-notifications/
   *     b. insert postgres ip_addresses.ip
   *     c. insert postgres user_actions
   *        - action_type: PRESENCE
   *        - action: ACTIVE
   *        - ip_address_id
   *        - device
   *        - browser
   *        - browser_version
   *        - operating_system
   *        - operating_system_version
   *        - clientUUID
   */
}

export async function end({ userId, userAgent, ip, clientUUID }) {
  /*
   * 1. find redis userId:clientUUID key
   *   if found
   *    a. destroy it
   *    b. insert user_actions
   *        - action_type: PRESENCE
   *        - action: AWAY
   *        - ip_address_id
   *        - device
   *        - browser
   *        - browser_version
   *        - operating_system
   *        - operating_system_version
   *        - clientUUID
   *   else do nothing
   *
   */
}
