import axios from 'axios'
import config from '../config'
import {
  getTutorBotSessionMessagesBySessionId,
  insertTutorBotSessionMessage,
} from '../models/Session'
import { tutor_bot_session_user_type } from '../models/Session/pg.queries'
import logger from '../logger'

interface TutorBotSessionMessage {
  tutorBotSessionUserType: tutor_bot_session_user_type
  message: string
  createdAt: Date
}

interface TutorBotSessionTranscript {
  sessionId: string
  messages: TutorBotSessionMessage[]
}

export const getTranscript = async (
  sessionId: string
): Promise<TutorBotSessionTranscript> => {
  const messagesInOrder = await getTutorBotSessionMessagesBySessionId(sessionId)
  return {
    sessionId,
    messages: messagesInOrder.map(m => m as TutorBotSessionMessage),
  }
}

const getBotResponseMessage = (conversation: string): string => {
  const messages = conversation.split('<|end|>')
  return removeTurnMarkers(messages[messages.length - 1])
}

export const sendMessageAndGetUpdatedTranscript = async (
  sessionId: string,
  message: string
) => {
  // Save the latest user message to DB and create the transcript of the conversation so far
  await insertTutorBotSessionMessage(
    sessionId,
    removeTurnMarkers(message),
    'student'
  )
  const transcript = await getTranscript(sessionId)
  const prompt = createPromptFromTranscript(transcript)
  const completion = await createChatCompletion(prompt, sessionId)
  const botMessage = getBotResponseMessage(completion)

  // Save bot response to session messages and append to the existing transcript
  const savedBotMessage = await insertTutorBotSessionMessage(
    sessionId,
    botMessage,
    'bot'
  )
  transcript.messages.push({
    tutorBotSessionUserType: 'bot',
    message: botMessage,
    createdAt: savedBotMessage.createdAt,
  } as TutorBotSessionMessage)
  return transcript
}

/**
 * Returns text generated by the Tutor Bot for the given prompt
 */
const createChatCompletion = async (
  prompt: string,
  sessionId: string
): Promise<string> => {
  try {
    const res = await axios.post(
      config.tutorBotBaseUrl,
      {
        inputs: prompt,
      },
      {
        headers: {
          Authorization: `Bearer ${config.tutorBotApiKey}`,
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
      }
    )
    return res.data[0].generated_text
  } catch (err) {
    logger.error(
      {
        sessionId,
        error: err,
      },
      'Failed to get Tutor Bot response'
    )
    throw new Error('Could not get Tutor Bot response')
  }
}

const createPromptFromTranscript = (
  transcript: TutorBotSessionTranscript
): string => {
  let prompt = ''
  transcript.messages.forEach(m => {
    const senderTag =
      m.tutorBotSessionUserType === 'bot' ? '<|assistant|>' : '<|user|>'
    prompt += `${senderTag}\n${m.message}<|end|>\n`
  })
  return prompt
}

/**
 * Removes chat turn markers from the string.
 * See https://huggingface.co/microsoft/Phi-3-medium-4k-instruct#chat-format
 */
const removeTurnMarkers = (text: string): string => {
  return text
    .replace(/<\|user\|>|<\|assistant\|>|<\|end\|>|\[\[NONE\]\]/g, '')
    .trim()
}
