export const USER_ACTION_TYPES = {
  QUIZ: 'QUIZ',
  SESSION: 'SESSION',
  ACCOUNT: 'ACCOUNT',
  ADMIN: 'ADMIN',
}
export type USER_ACTION_TYPES = typeof USER_ACTION_TYPES[keyof typeof USER_ACTION_TYPES]

export const QUIZ_USER_ACTIONS = {
  STARTED: 'STARTED QUIZ',
  PASSED: 'PASSED QUIZ',
  FAILED: 'FAILED QUIZ',
  VIEWED_MATERIALS: 'VIEWED REVIEW MATERIALS',
  UNLOCKED_SUBJECT: 'UNLOCKED SUBJECT',
}
export type QUIZ_USER_ACTIONS = typeof QUIZ_USER_ACTIONS[keyof typeof QUIZ_USER_ACTIONS]

export const SESSION_USER_ACTIONS = {
  REQUESTED: 'REQUESTED SESSION',
  JOINED: 'JOINED SESSION',
  REJOINED: 'REJOINED SESSION',
  ENDED: 'ENDED SESSION',
  REPLIED_YES: 'REPLIED YES TO TEXT',
  TIMED_OUT_15_MINS: '15 MIN TIME OUT',
  TIMED_OUT_45_MINS: '45 MIN TIME OUT',
}
export type SESSION_USER_ACTIONS = typeof SESSION_USER_ACTIONS[keyof typeof SESSION_USER_ACTIONS]

export const ACCOUNT_USER_ACTIONS = {
  CREATED: 'CREATED',
  UPDATED_AVAILABILITY: 'UPDATED AVAILABILITY',
  UPDATED_PROFILE: 'UPDATED PROFILE',
  ADDED_PHOTO_ID: 'ADDED PHOTO ID',
  ADDED_REFERENCE: 'ADDED REFERENCE',
  COMPLETED_BACKGROUND_INFO: 'COMPLETED BACKGROUND INFORMATION',
  DELETED_REFERENCE: 'DELETED REFERENCE',
  APPROVED: 'APPROVED',
  ONBOARDED: 'ONBOARDED',
  SUBMITTED_REFERENCE_FORM: 'SUBMITTED REFERENCE FORM',
  REJECTED_PHOTO_ID: 'REJECTED PHOTO ID',
  REJECTED_REFERENCE: 'REJECTED REFERENCE',
  BANNED: 'BANNED',
  DEACTIVATED: 'DEACTIVATED',
  VOLUNTEER_FAVORITED: 'VOLUNTEER FAVORITED',
  VOLUNTEER_UNFAVORITED: 'VOLUNTEER UNFAVORITED',
}
export type ACCOUNT_USER_ACTIONS = ACCOUNT_USER_ACTIONS[keyof typeof ACCOUNT_USER_ACTIONS]

export const USER_ACTION = {
  TYPE: USER_ACTION_TYPES,
  QUIZ: QUIZ_USER_ACTIONS,
  SESSION: SESSION_USER_ACTIONS,
  ACCOUNT: ACCOUNT_USER_ACTIONS,
}

// new format to move to from USER_ACTIONS
// user events in a [noun][verb] format
export const EVENTS = {
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_APPROVED: 'ACCOUNT_APPROVED',
  ACCOUNT_ONBOARDED: 'ACCOUNT_ONBOARDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  FRIEND_REFERRED: 'FRIEND_REFERRED',
  PHOTO_ID_REJECTED: 'PHOTO_ID_REJECTED',
  REFERENCE_DELETED: 'REFERENCE_DELETED',
  REFERENCE_REJECTED: 'REFERENCE_REJECTED',
  SESSION_JOINED: 'SESSION_JOINED',
  SESSION_MATCHED: 'SESSION_MATCHED',
  SESSION_REJOINED: 'SESSION_REJOINED',
  SUBJECT_UNLOCKED: 'SUBJECT_UNLOCKED',
  SESSION_REPLIED_YES_TO_TEXT: 'SESSION_REPLIED_YES_TO_TEXT', // @note: currently deprecated
}

export const USER_BAN_REASONS = <const>[
  'NON US SIGNUP',
  'USED BANNED IP',
  'SESSION REPORTED',
  'BANNED SERVICE PROVIDER',
  'ADMIN',
]
export type USER_BAN_REASONS = typeof USER_BAN_REASONS[number]

export enum IP_ADDRESS_STATUS {
  OK = 'OK',
  BANNED = 'BANNED',
}

export const STATUS = <const>{
  SUBMITTED: 'SUBMITTED',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
}

export const PHOTO_ID_STATUS = {
  EMPTY: 'EMPTY',
  SUBMITTED: STATUS.SUBMITTED,
  REJECTED: STATUS.REJECTED,
  APPROVED: STATUS.APPROVED,
}

export const REFERENCE_STATUS = {
  UNSENT: 'UNSENT',
  SENT: 'SENT',
  SUBMITTED: STATUS.SUBMITTED,
  REJECTED: STATUS.REJECTED,
  APPROVED: STATUS.APPROVED,
}

export enum VERIFICATION_METHOD {
  SMS = 'sms',
  EMAIL = 'email',
}

export enum ONBOARDING_STATUS {
  ONBOARDED = 'Onboarded',
  DEACTIVATED = 'Deactivated',
  INACTIVE = 'Inactive',
  IN_PROGRESS = 'In progress',
  NOT_STARTED = 'Not started',
}

export enum GRADES {
  EIGHTH = '8th',
  NINTH = '9th',
  TENTH = '10th',
  ELEVENTH = '11th',
  TWELVETH = '12th',
  COLLEGE = 'College',
  OTHER = 'Other',
}
